### ISSUE TITLE
Portability issue

### ISSUE THREAD

**Issue by davgothic** [salemove/gojo#1]
Your usage of the sed command is macOS specific, in that the -i flag differs in usage between GNU sed and macOS sed.

When I run the first kata on Ubuntu 18.04 I get the following error:

`$ ./start`
`sed: can't read : No such file or directory`

[See this stackoverflow post on the subject.](https://stackoverflow.com/questions/43171648/sed-gives-sed-cant-read-no-such-file-or-directory)

**Comment by deiwin** [comment]
Thanks for the report. Will fix.

**Comment by deiwin** [comment]
Can you try again please?

**Comment by davgothic** [comment]
All is fine now :+1: 

Thanks!
